# fly.toml app configuration file generated for cal-api on 2023-10-26T18:41:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cal-api"
primary_region = "ams"

[build]
  dockerfile = "apps/api/Dockerfile"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
